FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

ENV DATABASE_URL mongodb://root:root1234@ds111066.mlab.com:11066/covid
ENV TIME_OFFSET "+0000"
ENV CRON_FREQUENCY "0/15 * * * * *"
ENV PORT 5000

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE ${PORT}
CMD [ "node", "index.js" ]